package net.k1ra.succubotserver.feature.api.utils


//Setting keys
const val KEY_ENABLE_LDAP_LOGIN = "ENABLE_LDAP_LOGIN"
const val KEY_LDAP_SERVER = "LDAP_SERVER"
const val KEY_LDAP_BIND_USER = "LDAP_BIND_USER"
const val KEY_LDAP_BIND_PASSWORD = "LDAP_BIND_PASSWORD"
const val KEY_LDAP_TLS = "LDAP_TLS"
const val KEY_LDAP_ADMIN_GROUP_NAME = "LDAP_ADMIN_GROUP_NAME"
const val KEY_LDAP_GROUP_DN = "LDAP_GROUP_DN"
const val KEY_LDAP_GROUP_FILTER = "LDAP_GROUP_FILTER"
const val KEY_LDAP_USER_DN = "LDAP_USER_DN"
const val KEY_LDAP_USER_FILTER = "LDAP_USER_FILTER"
const val KEY_LDAP_USER_UID_ATTRIBUTE = "LDAP_USER_UID_ATTRIBUTE"
const val KEY_MIN_PASSWORD_LENGTH = "MIN_PASSWORD_LENGTH"
const val KEY_MAX_IMAGE_SIZE = "MAX_IMAGE_SIZE"
const val KEY_CURRENT_BASE_URL = "CURRENT_BASE_URL"
const val KEY_MQTT_CERTIFICATE = "MQTT_CERTIFICATE"
const val KEY_MQTT_SERVER = "MQTT_SERVER"